"use client"
import { motion } from "framer-motion"
import { Play } from "lucide-react"
import { Pill } from "@/components/ui/pill"
import { Stat } from "@/components/ui/stat"
import { LeadForm } from "@/components/lead-form"
import { BRAND_BLUE, BRAND_ORANGE } from "@/lib/constants"

interface HeroProps {
  onWatchDemo: () => void
}

export function Hero({ onWatchDemo }: HeroProps) {
  return (
    <section className="relative overflow-hidden">
      <div
        className="absolute inset-0 z-[-1]"
        style={{
          background: `radial-gradient(1200px 600px at 10% -10%, ${BRAND_BLUE}15, transparent), radial-gradient(1000px 500px at 120% 10%, ${BRAND_ORANGE}20, transparent)`,
        }}
      />
      <div className="max-w-7xl mx-auto px-4 pt-16 pb-8 grid md:grid-cols-2 gap-10 items-center">
        <div>
          <div className="flex flex-wrap gap-2 mb-4">
            <Pill>Commission: 30%</Pill>
            <Pill>$0.10 per QR</Pill>
            <Pill>Simple Plug & Print</Pill>
            <Pill>Variable QR‑Codes</Pill>
          </div>
          <motion.h1
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-4xl md:text-5xl font-bold leading-tight"
          >
            Grow Your Print Business with Engage360
          </motion.h1>
          <p className="mt-4 text-lg text-slate-700 max-w-xl">
            Offer your brand clients <strong>product authentication</strong>, <strong>customer rewards</strong>, and{" "}
            <strong>first‑party data capture</strong> — all powered by unique, variable QR codes generated by our{" "}
            <em>Simple Plug & Print</em> software.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <button
              onClick={onWatchDemo}
              className="inline-flex items-center gap-2 rounded-xl px-4 py-2 font-semibold text-white shadow-lg"
              style={{ backgroundColor: BRAND_BLUE }}
            >
              <Play className="w-4 h-4" /> Watch Partner Demo
            </button>
            <a
              href="#apply"
              className="inline-flex items-center gap-2 rounded-xl px-4 py-2 font-semibold border"
              style={{ borderColor: BRAND_BLUE, color: BRAND_BLUE }}
            >
              Apply as Printing Partner
            </a>
          </div>
          <div className="mt-8 grid grid-cols-3 gap-6">
            <Stat value="30%" label="Commission on every QR" />
            <Stat value="$0.10" label="Flat price per QR" />
            <Stat value="5 steps" label="Plug → Print → Earn" />
          </div>
        </div>
        <div className="bg-white rounded-2xl p-6 shadow-xl ring-1 ring-slate-200">
          <h3 className="text-xl font-semibold mb-4">Apply to Join</h3>
          <LeadForm />
        </div>
      </div>
    </section>
  )
}
